apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: grpc-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: iamtanya/grpc-client:latest
