apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-server-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: quote-server
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: quote-server
    spec:
      containers:
        - name: quote-server
          image: iamtanya/quote-server:latest
          ports:
            - containerPort: 50052
